# SVOA Lea Platform - Development Environment
# EU/EES compliant local development setup

version: '3.8'

services:
  # PostgreSQL with pgvector for OLTP and RAG
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: svoa_lea_dev
      POSTGRES_USER: svoa_user
      POSTGRES_PASSWORD: dev_password_change_in_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U svoa_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for job queues and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MinIO for S3-compatible object storage (development)
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: svoa_admin
      MINIO_ROOT_PASSWORD: dev_password_change_in_prod
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Development API server (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://svoa_user:dev_password_change_in_prod@postgres:5432/svoa_lea_dev
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
      - ENVIRONMENT=development
      - EU_REGION=eu-north-1
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

  # Frontend development server (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ENVIRONMENT=development
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app/frontend
      - ./components:/app/components

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default:
    name: svoa_lea_network
    driver: bridge